context("Truncation")

n <- 100
set.seed(233); beta_all <- rtruncbeta(n, shape1=3, shape2=4)
set.seed(233); beta_trunc <- rtruncbeta(n, shape1=3, shape2=4, a=.2, b=.6)
set.seed(233); binom_all <- rtruncbinom(n, size=8, prob=.18)
set.seed(233); binom_trunc <- rtruncbinom(n, size=8, prob=.18, a=1, b=3)
set.seed(233); chisq_all <- rtruncchisq(n, df=375)
set.seed(233); chisq_trunc <- rtruncchisq(n, df=375, a=360, b=390)
set.seed(233); contb_all <- rtrunccontbern(n, lambda=.317)
set.seed(233); contb_trunc <- rtrunccontbern(n, lambda=.317, a=.4, b=.7)
set.seed(233); exp_all <- rtruncexp(n, rate=.37)
set.seed(233); exp_trunc <- rtruncexp(n, rate=.37, a=4, b=7)
set.seed(233); gamma1_all <- rtruncgamma(n, shape=5, rate=3)
set.seed(233); gamma1_trunc <- rtruncgamma(n, shape=5, rate=3, a=1.5, b=2)
set.seed(233); gamma2_all <- rtruncgamma(n, shape=5, scale=3)
set.seed(233); gamma2_trunc <- rtruncgamma(n, shape=5, scale=3, a=7, b=9)
set.seed(233); igamma1_all <- rtruncinvgamma(n, shape=5, rate=3)
set.seed(233); igamma1_trunc <- rtruncinvgamma(n, shape=5, rate=3, a=.5, b=.6)
set.seed(233); igamma2_all <- rtruncinvgamma(n, shape=5, scale=3)
set.seed(233); igamma2_trunc <- rtruncinvgamma(n, shape=5, scale=3, a=.1, b=.2)
set.seed(233); igauss_all <- rtruncinvgauss(n, m=31, s=74)
set.seed(233); igauss_trunc <- rtruncinvgauss(n, m=31, s=74, a=0, b=1)
set.seed(233); lnorm_all <- rtrunclnorm(n, meanlog=0, sdlog=.7)
set.seed(233); lnorm_trunc <- rtrunclnorm(n, meanlog=0, sdlog=.7, a=3, b=4)
# TODO #59: uncomment below once #55 is resolved
# set.seed(233); nbinom_all <- rtruncnbinom(n, size=63, prob=.62)
# set.seed(233); nbinom_trunc <- rtruncnbinom(n, size=63, prob=.62, a=1, b=3)
set.seed(233); norm_all <- rtruncnorm(n, mean=81, sd=49)
set.seed(233); norm_trunc <- rtruncnorm(n, mean=81, sd=49, a=50, b=99)
set.seed(233); pois_all <- rtruncpois(n, lambda=95)
set.seed(233); pois_trunc <- rtruncpois(n, lambda=95, a=100, b=101)
test_that("Truncation limits are working as expected", {
	expect_setequal(beta_all[beta_all >= .2 & beta_all <= .6], beta_trunc)
	expect_setequal(binom_all[binom_all >= 1 & binom_all <= 3], binom_trunc)
	expect_setequal(chisq_all[chisq_all >= 360 & chisq_all <= 390], chisq_trunc)
	expect_setequal(contb_all[contb_all >= .4 & contb_all <= .7], contb_trunc)
	expect_setequal(exp_all[exp_all >= 4 & exp_all <= 7], exp_trunc)
	expect_setequal(gamma1_all[gamma1_all >= 1.5 & gamma1_all <= 2], gamma1_trunc)
	expect_setequal(gamma2_all[gamma2_all >= 7 & gamma2_all <= 9], gamma2_trunc)
	expect_setequal(igamma1_all[igamma1_all >= .5 & igamma1_all <= .6], igamma1_trunc)
	expect_setequal(igamma2_all[igamma2_all >= .1 & igamma2_all <= .2], igamma2_trunc)
	expect_setequal(igauss_all[igauss_all >= 0 & igauss_all <= 1], igauss_trunc)
	expect_setequal(lnorm_all[lnorm_all >= 3 & lnorm_all <= 4], lnorm_trunc)
	# TODO #59: make test for nbinom once #55 is fixed
	expect_setequal(norm_all[norm_all >= 50 & norm_all <= 99], norm_trunc)
	expect_setequal(pois_all[pois_all >= 100 & pois_all <= 101], pois_trunc)
})
