# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

# ======================================================== #
# Determines when the action is triggered                  #
# ======================================================== #

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# ======================================================== #
# Determine actions to take                                #
# ======================================================== #

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} ${{ matrix.config.r }}
    strategy:
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: ubuntu-devel, r: 'devel'}
    steps:
      # Checking out code -------------------------------------- #
      - uses: actions/checkout@master
      # Setting up environment --------------------------------- #
      - name: Setting up R ${{ matrix.config.r }} on ${{ matrix.config.os }}
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
      # Installing dependencies -------------------------------- #
      - name: Installing dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      # Checking package --------------------------------------- #
      - name: Checking package
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
